		<?php $this->headTitle('Author settings'); ?>
		<?php /* echo $this->headLink()->appendStylesheet($this->baseUrl . 'design/css/user/style.css');*/?>
  		<?php $this->headScript()->appendFile($this->baseUrl . '/js/jquery.js');?>
		<?php $this->headScript()->appendFile($this->baseUrl . '/js/author/settings.js');?>
		<?php /*$this->headScript()->appendFile($this->baseUrl . '/js/typeahead.min.js');*/?>
		<div id="content">
			<?php echo $this->formSettings; ?><br>
			<?php echo $this->message; ?>
		</div>
		<div id="link_forget_pass">
            <p><a href="<?php echo $this->url(array(), 'logout'); ?>">Выйти</a></p>
		</div>
		<div>
			<script type="text/javascript">
				 $(document).ready(function(){

					$("#payment_num").attr('disabled','disabled');
					$("#id").attr('disabled','disabled');
					$("#email").attr('disabled','disabled');
						 
					$("#payment_name").change(function(){	
						$("#payment_num").val('');
						var data = $("#payment_name").val();
						if (data > 0)
						{
							$("#payment_num").removeAttr('disabled');
							
							$.ajax({
								url: './populate-payment-num/author/',
								type: 'POST',
								data: {param : data},
								dataType: "json",
								success: function(data)
								{
									if (data.param != null)
										$("#payment_num").val(data.param)
									else
										$("#payment_num").val("");
								}
							});
						}
						else
						{
							$("#payment_num").val("");	
							$("#payment_num").attr('disabled','disabled');
						}
					});	

					$("#save_payment").click(function(){
						var paymentName = $("#payment_name").val();
						var paymentNum = $("#payment_num").val();
						if (paymentName > 0 && paymentNum != null)
						{
							$.ajax({
								url: './update-payment-num/author/',
								type: 'POST',
								data: {param1 : paymentName, param2 : paymentNum},
								dataType: "json",
								success: function(data)
								{
									if (data == 1)
									{
										alert("Сохранено!");
										$("#payment_name").val('');
										$("#payment_num").val('');
										$("#payment_num").attr('disabled','disabled');
									}
								}
							});
						}
						else
							alert("Выберите кошелек!");


						});				
					
				 });
			</script>
		</div>
