<?php echo $this->doctype() ?> 
<html>
 <head>
  <?php echo $this->headTitle('Index page'); ?>
  <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8'); ?>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl . 'design/css/style.css'); ?>
  <?php echo $this->headScript(); ?>
</head>
<body>
    <div id="main">
        <div id="content">
			<?php 
				if ($this->type_rules == 'client_rules') 
					echo $this->render('client_rules.phtml');
				else
					echo $this->render('author_rules.phtml');
			?>
        </div>
    </div>
</body>
</html>

